### ISSUE TITLE
Win App Logo Change

### ISSUE THREAD

**Issue by aeliot** [openthread/openthread#1477]
The windows app currently uses the Thread Group logo. (https://github.com/openthread/openthread/tree/master/etc/visual-studio/Assets)
These logos should probably be changed to the OT logo, since this app is by OpenThread and not by the Thread Group.

**Comment by nibanks** [comment]
Can someone point me to an image file of 'the OT logo'? As indicated in the link above, we need multiple sized, from a small icon to a splash screen.

**Comment by aeliot** [comment]
The full OpenThread logo can be found in the docs folder, I'm working on getting the sort OT logo

**Comment by beriberikix** [comment]
![icon_1264x1024_v2](https://cloud.githubusercontent.com/assets/178376/24060249/a52c42b6-0b0f-11e7-9a8a-85c6b8d5022a.png)

**Comment by beriberikix** [comment]
Here's a high-res logo. I have it as a .ai if you want multiple sizes, just need to know the resolutions.

**Comment by nibanks** [comment]
I need the following sizes:

Icon
- 24 x 24
- 48 x 48
- 50 x 50
- 88 x 88
- 300 x 300

Splash Screen
- 620 x 300
- 1240 x 600

**Comment by beriberikix** [comment]
Do you want the "OT" logo for all sizes?

**Comment by nibanks** [comment]
I'm fine with either that or the 'OpenThread' logo for the Splash Screen images.

**Comment by beriberikix** [comment]
I haven't spent this much time in Illustrator in a while...does these work?

![otlogo_1240x600](https://cloud.githubusercontent.com/assets/178376/24067427/bffa9316-0b39-11e7-8487-2de84e3ab66a.png)
![otlogo_620x300-01](https://cloud.githubusercontent.com/assets/178376/24067428/bffacc6e-0b39-11e7-9a9c-96418d3eaabc.png)
![oticon_300x300](https://cloud.githubusercontent.com/assets/178376/24067431/bffc8b8a-0b39-11e7-83fa-40626d9ff38c.png)
![oticon_24x24](https://cloud.githubusercontent.com/assets/178376/24067429/bffb2966-0b39-11e7-969e-f14e96e9b6f5.png)
![oticon_48x48](https://cloud.githubusercontent.com/assets/178376/24067430/bffc6484-0b39-11e7-8910-bf5aaa2872f0.png)
![oticon_50x50](https://cloud.githubusercontent.com/assets/178376/24067432/bffdab64-0b39-11e7-90c3-3a1e76e21ff1.png)
![oticon_88x88](https://cloud.githubusercontent.com/assets/178376/24067433/c00d305c-0b39-11e7-9148-77f4b6e54a86.png)

**Comment by beriberikix** [comment]
[winapp_images.zip](https://github.com/openthread/openthread/files/855579/winapp_images.zip)

Adding as a .zip as well.

**Comment by nibanks** [comment]
The logos look pretty good except with the default color when pinned to the start menu. Looks good when pinned to task bar. 

![image](https://cloud.githubusercontent.com/assets/20663557/24121001/d874e1da-0d73-11e7-83af-397a94bb014b.png)

![image](https://cloud.githubusercontent.com/assets/20663557/24121024/ed464cde-0d73-11e7-8c53-c22f5c6679e7.png)

**Comment by turon** [comment]
@nibanks Is there a way to specify that white should be used as the default background on Win desktop?  The .png is just defining the transparent parts, so the background color is likely metadata of some sort in the desktop config.

**Comment by nibanks** [comment]
I updated my PR #1489 use a white background.

**Comment by aeliot** [comment]
@nibanks could you also update the screenshots in /doc/images?  The following still have the old background:
windows-app-interface-list.png
windows-app-talk-client.png
windows-app-talk-server.png

**Comment by jwhui** [comment]
Addressed by #1529.
